### ISSUE TITLE
Add configuration: Path at which the WebSocket listener listens on the host

### ISSUE THREAD

**Issue by PhilLehmann** [vert-x3/vertx-eventbus-bridge-clients#10]
Right now, it's hardcoded.

**Comment by vietj** [comment]
that's rather an issue for the event bus bridge server in vertx-web, isn't it ?

**Comment by philrykoff** [comment]
For both sides, imho.

I was thinking about the code at 

https://github.com/vert-x3/vertx-eventbus-bridge-clients/blob/java-client/java/src/main/java/io/vertx/ext/eventbus/client/transport/WebSocketTransport.java#L35. 

There,  `"/eventbus/websocket"` is currently hardcoded - this should be made configurable as the path of the SockJS bridge is configurable, too.

`router.route("/eventbus/*").handler(sockJSHandler);`
