### ISSUE TITLE
EventBusClient configuration

### ISSUE THREAD

**Issue by PhilLehmann** [vert-x3/vertx-eventbus-bridge-clients#14]
While I already created a few tickets in regards to **what** new things to configure, this ticket is primarily about **how** to configure.

In my own client implementation, I make use of `HttpClientOptions `to configure quite a number of settings for my `httpClient.webSocket(...)`.

For `EventBusClient`, I think it makes sense to create a similar class / class structure, e.g. 
- `EventBusClientOptions `(e.g., path, idle timeout, proxy, default DeliveryOptions.timeout, maybe also port / host, ...) 
- and then one specific for each transport, e.g. 
  - `TcpEventBusClientOptions `and 
  - `WebSocketEventBusClientOptions `(MaxWebsocketFrameSize, ssl, trust store options, verifyHost, ...).

I propose new factory method overloads, e.g.:

- EventBusClient websocket(int port, String host, WebSocketEventBusClientOptions options);

and / or simply 

- EventBusClient websocket(WebSocketEventBusClientOptions options);

I hereby RfC 😁

**Comment by vietj** [comment]
+1

I'm wondering wether we should use inheritance or instead of a `TransportOptions` that is part of `EventBusClientOptions`

**Comment by philrykoff** [comment]
Your proposal indeed has a few advantages over my idea.

+1

**Comment by philrykoff** [comment]
If you like, current status is available here: https://github.com/philrykoff/vertx-eventbus-bridge-clients/tree/java-client/java/src/main/java/io/vertx/ext/eventbus/client

The files EventBusClientOptions.java and options/* are related to this issue. Additionally, I propose the following changes to EventBusClient ctors: https://github.com/philrykoff/vertx-eventbus-bridge-clients/blob/java-client/java/src/main/java/io/vertx/ext/eventbus/client/EventBusClient.java#L36-L66.

I am not finished with the ProxyOptions and TrustOptions, but I'd like to get some opinions on the overall direction first.

**Comment by philrykoff** [comment]
I'll now add some tests.
