### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by PhilLehmann** [vert-x3/vertx-eventbus-bridge-clients#16]
While digging into how VertX internally handles proxies, I figured that there seems to be a general case -
 NetClient and HttpClient making use of either https://github.com/eclipse/vert.x/blob/a30703379a06502faaae0aeda1eaa9a9b1152004/src/main/java/io/vertx/core/net/impl/ChannelProvider.java or https://github.com/eclipse/vert.x/blob/a30703379a06502faaae0aeda1eaa9a9b1152004/src/main/java/io/vertx/core/net/impl/ProxyChannelProvider.java.

In addition to that, there seems to be a special case for non-tls HTTP calls to an HTTP proxy:
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java#L992-L1011

Does anyone know a reason for this special case being there?

**Comment by philrykoff** [comment]
Implementation is done for HTTP, SOCKS4/5.

I created test cases for HTTP only (so only for WebSocket client) by adding LittleProxy as a test dependancy. I could find a similar java based SOCKS proxy. Tips are appreciated 😄 

Connecting to SSL servers via HTTP proxies is currently blocked by netty issue https://github.com/netty/netty/issues/5070. There apparently seems to be a PR available, but it was not merged for some time. Does anyone of you by chance have contacts to the netty team to put this on their agenda?
