### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by PhilLehmann** [vert-x3/vertx-eventbus-bridge-clients#17]
While adding tests, I thought that logging might be helpful.

As I did not find another VertX lib which logs, I'd like to gather opinions first. As we cannot use VertX's LoggerFactory, due to that being a Java 8 (soon 9) dependency, what would be the favoured logging framework?

JUL, as it is included in the Java Runtime (no overhead) vs SLF4J & Logback (flexibility)?

It seems that netty itself supports various logging frameworks - it might be beneficial to choose one that netty also supports, if we want to keep the option to enable netty internal logging  (http://netty.io/3.7/api/org/jboss/netty/logging/package-summary.html).

**edit: To keep the embedded IoT agents small and to heat up the debate, I would prefer JUL ;-)**

**Comment by vietj** [comment]
Make an internal small logger abstraction implemented by SLF and JUL.
Set SLF as a optional dependency.
When you need the logger try to obtain the SLF implementation via reflection (i.e without referencing the class), if it does not work fallback on JUL.

**Comment by philrykoff** [comment]
I had a look at how VertX itself does logging. It defaults to JUL and uses other loggers like SLF if configured.

I largely migrated the code from VertX core to eventbus-bridge-clients, so that it can be configured and used just the same. I'll pr real soon now.

**Comment by vietj** [comment]
rather look at Netty in this case

**Comment by philrykoff** [comment]
My reasoning was to have the same logging API as other VertX modules have, to make it easier for other VertX devs to use this module (e.g., the system properties LOGGER_DELEGATE_FACTORY_CLASS_NAME and vertx-default-jul-logging.properties, default config file vertx-default-jul-logging.properties). 

But I will change the implementation if netty has any benefits. Maybe we can keep the VertX similarities and adopt any improvements from netty.
