### ISSUE TITLE
Restore Java 7 compatibility

### ISSUE THREAD

**Issue by PhilLehmann** [vert-x3/vertx-eventbus-bridge-clients#20]
There are a few issues which make this project unfit for Java 7 right now:

- two calls to ConcurrentMap.compute in EventBusClient
To add insult to injury, my current PR added:
- many non-final variables being used in anonymous inner classes
- a call to Set.forEach in EventBusClient

I didn't catch them as I used Java 8 during development for testing the library against VertX bridges. ☹️

**Comment by vietj** [comment]
there is profile in pom.xml to run with java 7

**Comment by philrykoff** [comment]
I could not find build profiles in the current POM (but I also never worked with them ;()

https://github.com/vert-x3/vertx-eventbus-bridge-clients/blob/java-client/java/pom.xml

Anyhow, I fixed my own mistakes and will roll back your changes from the following commit with my next commit if that is ok for you?

https://github.com/vert-x3/vertx-eventbus-bridge-clients/pull/18/commits/c3c751cfbd19a6e3a4f2a19978b60f92d50a5616
