### ISSUE TITLE
Improve python support

### ISSUE THREAD

**Issue by WolfgangFahl** [vert-x3/vertx-eventbus-bridge-clients#39]
#### Describe the feature

Improve official support for python

#### Use cases

Any python user wanting to use vert.x especially without using a Java server.

#### Contribution

* https://github.com/rc-dukes/vertx-eventbus-python
* https://pypi.org/project/vertx-python-client/

The docs say "There is no official support for python in Vert.x since there is no maintainer". There are the two above projects which unfortunately are not well integrated with the Vert.x eco system. Improving the integration is IMHO worthwhile.

**Comment by gaol** [comment]
I am willing to give it a try to improve. :) What I want to start with is a project which can be used for [testing the clients](https://github.com/gaol/test-eventbus-bridge).

To be clear that the bridge server needs to run on JVM, what we can improve is just the Python client.

I am gonna start on branch https://github.com/gaol/vertx-eventbus-bridge-clients/tree/python-improvment, please feel free to comment any time :)

**Comment by WolfgangFahl** [comment]
@gaol  - thank you for picking this up.

I'd recommend a stand alone python project for better CI integration and documentation. Trying to stay in the full java github tree is IMHO a major obstacle to making this a success. 

From next week on i'd be available for an online session to discuss the current state of affairs. Feel free to get in touch via any of my social links.
