### ISSUE TITLE
Websocket in vertx-eventbus.js disconnects when Chrome Tab idle for 5 minutes due to Intensive Throttling

### ISSUE THREAD

**Issue by dilansankalpa** [vert-x3/vertx-eventbus-bridge-clients#51]
### Version

"@vertx/eventbus-bridge-client.js": "1.0.0"
Chrome 89 onwards

### Context

vertx-eventbus.js use setInterval to send a periodic ping via the sockjs websocket to keep the health. But when the tab is idle for 5 minutes this ping will not be sent due to suspension of chained timers.
https://developer.chrome.com/blog/timer-throttling-in-chrome-88/
So websocket get disconnected.

```
EventBus.prototype.enablePing = function (enable) {    var self = this;
    if (enable) {      var sendPing = function () {        self.sockJSConn.send(JSON.stringify({ type: 'ping' }));      };
      if (self.pingInterval &gt; 0) {        // Send the first ping then send a ping every pingInterval milliseconds        sendPing();        self.pingTimerID = setInterval(sendPing, self.pingInterval);      }    } else {      if (self.pingTimerID) {        clearInterval(self.pingTimerID);        self.pingTimerID = null;      }    }  };
```

### Steps to reproduce

1. Create an new EventBus Object and Register
2. Make the Chrome Tab Idle for 5 minutes
3. Websocket disconnects

**Comment by vietj** [comment]
can you contribute a fix @dilansankalpa ?

**Comment by pmlopes** [comment]
I guess the "fix" here is to change the ping timeout depending on the state. If we use:

https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

We can know if a page in visible or not, and in that case we can throttle the ping requests, initially a few times per minute and later once every 2 minutes or so, so the timer will be activated as described in the rules here:

https://developer.chrome.com/blog/timer-throttling-in-chrome-88/

**Comment by dilansankalpa** [comment]
@pmlopes @vietj Yes we can try changing the ping timeout depending on the state. But when the pings are missed, websocket disconnection is triggered by a message sent to the client from the server side. I believe that is sent by SockJs server side. 

For one other application where a similar ping is sent as a http request (xmr or fetch), i was able to schedule the ping even when the tab is idle in following manner. 
Using setTimeout to schedule timer recursively after the response comes for one http ping. When response comes clear the previous timeout and schedule the next setTimeout. Then it is not detected as a chained timer. 

`sendPing() {
    clearTimeout(this.pingTimer);
    fetch('<url>')
        .then((response) => {
            console.log("sent ping");
        }).catch((response) => {
        console.log("failed to send ping");
    }).finally(()=>{
        this.schedulePing(5000);
    });
}

schedulePing(interval){
    this.pingTimer = setTimeout(()=>{ this.sendPing(); },
        interval);
}`

But in websocket as we do not get a responnse in async manner, Event setTimeout is used, browser detects as the timer is chained.

**Comment by dilansankalpa** [comment]
@vietj I have overcome the issue by disabling the ping inside "eventbus-bridge-client.js". From the library function is needed to sendPing

```
EventBus.prototype.sendPing = function () {
    var self = this;
    self.sockJSConn.send(JSON.stringify({ type: 'ping' }));
  };
```

Externally i have disable the ping in websocket onOpen 
```
eventBus.enablePing(false);
```

And i used a webworker to schedule the timer. Chrome Intensive Throttling does not suspend timers in web workers. Web worker will send periodic message to the application and application will send Eventbus pings in onmessage events of the web worker.

So as a fix providing EventBus.prototype.sendPing will be suffitient. @vietj Is this acceptable?

**Comment by vietj** [comment]
it looks reasonnable
