### ISSUE TITLE
Support Vert.x 4.x

### ISSUE THREAD

**Issue by leotu** [vert-x3/vertx-eventbus-bridge-clients#52]
i,e. "<vertx.version>4.1.2</vertx.version>"

1. Test codes:

- io.vertx.eventbusclient.test.TcpBusTest.java compiled failed:
vertx.eventBus().send(...) should change to vertx.eventBus().request(...)

-  io.vertx.eventbusclient.test.WebSocketBusTest  compiled failed:
.requestHandler(router::accept) should change to .requestHandler(router::handle)

2. Missing file:
io.vertx.test.proxy.SocksProxy.java

**Comment by gaol** [comment]
We may need to create a branch of Java client for Vert.x 3 and move the master branch towards Vert.x 4.

**Comment by Ndepbesong45boy** [comment]
I am an Outreachy applicant @gaol  @pendula95  can this be assigned to me?

**Comment by sherrif10** [comment]
Hello @gaol @pmlopes , Incase this issue is ready for work , would love working on it.

**Comment by gaol** [comment]
sure, any contribution is welcome :)

**Comment by gaol** [comment]
@pmlopes I would like have a branch called `java-vertx-3` for vertx 3.x users, WDYT? :)

**Comment by pmlopes** [comment]
@gaol I think it's a good idea as we're trying to get everyone to be on vertx 4.

**Comment by Ako-Njang** [comment]
Hi @gaol  @pmlopes I have sent in a PR for this #63. With regards to point 2, the file `io.vertx.test.proxy.SocksProxy.java` is added automatically during test from the `vertx-core` dependency with test scope.
