### ISSUE TITLE
Add configuration: pingInterval

### ISSUE THREAD

**Issue by PhilLehmann** [vert-x3/vertx-eventbus-bridge-clients#9]
My own EventBus client pings only every 5 seconds, with which I didn't experience any issues. 

EventBusClient pings every 100ms. 

Due to the above and as user experience might vary based on strange firewalls, let's make this configurable.

Edit: maybe this only relates to WebSocket protocol.

**Comment by vietj** [comment]
WebSocket has its own optional ping not related to the application ping.

**Comment by philrykoff** [comment]
In my current client, I am indeed doing two different pings. Maybe the latter one may be called my application ping: only every 10 minutes, which results in the server refreshing the session, so it does not time out on inactivity. Then, there is this (simplified):

```
            vertx.setPeriodic(5 * 1000, handle -> {
                this.write("{ \"type\": \"ping\" }");
            });
```

Before I implemented that ping, the bridge disconnected me after 10 seconds of inactivity. Thats why imho, pinging every few seconds should typically be enough. But as some firewalls are very strict, maybe there is a use case for lower ping times in some environments.

**Comment by vietj** [comment]
the ping period time, actually depends on the vertx event bus bridge server, if you don't ping fast enough, the server will disconnect you.

the default ping timeout is 10 seconds on the server.

so 5 seconds should work, that being said, the overhead of a ping message is very low.
